name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pip/${{ hashFiles('{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pip/
      - run: make release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
